ARC-0031: Improving mappings
ProvableHQ/ARCs pull request #21
Opened 2022-10-05 21:22 UTC by evanmarshall

See discussion: https://github.com/AleoHQ/ARCs/discussions/20

2022-10-12 16:29 UTC, collinc97 requested changes

2022-10-12 16:29 UTC, collinc97 commented on arc-0031/README.md
> +topic: Language
Formatting to follow https://github.com/AleoHQ/ARCs/tree/master/arc-0001#specification
```suggestion
topic: Application
```

2025-02-02 17:20 UTC, d0cd commented
@evanmarshall thank you for the submission!
We're working on revamping the ARCs process and resolving past proposals.
To that end, is this effort still active?

We plan to either close or refresh this this PR on February 10th, 2024.

2025-02-10 16:31 UTC, d0cd commented
Closing due to lack of activity. 
Please feel free to re-open if it becomes active again!

2025-02-10 16:31 UTC, closed without merging